-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Buttons exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


cancel : Translations -> String
cancel translations =
    t translations "buttons.cancel"


confirm : Translations -> String
confirm translations =
    t translations "buttons.confirm"


delete : Translations -> String
delete translations =
    t translations "buttons.delete"


edit : Translations -> String
edit translations =
    t translations "buttons.edit"


newSnippet : Translations -> String
newSnippet translations =
    t translations "buttons.new_snippet"


newTerm : Translations -> String
newTerm translations =
    t translations "buttons.new_term"


newUser : Translations -> String
newUser translations =
    t translations "buttons.new_user"


signIn : Translations -> String
signIn translations =
    t translations "buttons.sign_in"


signOut : Translations -> String
signOut translations =
    t translations "buttons.sign_out"


source : Translations -> String
source translations =
    t translations "buttons.source"


submit : Translations -> String
submit translations =
    t translations "buttons.submit"


view : Translations -> String
view translations =
    t translations "buttons.view"
