-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Dialogs exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


confirmTitle : Translations -> String
confirmTitle translations =
    t translations "dialogs.confirm_title"
