-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Labels exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


loading : Translations -> String
loading translations =
    t translations "labels.loading"


noSnippets : Translations -> String
noSnippets translations =
    t translations "labels.no_snippets"


noTerms : Translations -> String
noTerms translations =
    t translations "labels.no_terms"


noUsers : Translations -> String
noUsers translations =
    t translations "labels.no_users"


onError : Translations -> String -> String
onError translations reason =
    tr translations Curly "labels.on_error" [ ( "reason", reason ) ]


onSignOut : Translations -> String
onSignOut translations =
    t translations "labels.on_sign_out"


videoThumbnail : Translations -> String
videoThumbnail translations =
    t translations "labels.video_thumbnail"
