-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Titles exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


home : Translations -> String
home translations =
    t translations "titles.home"


name : Translations -> String
name translations =
    t translations "titles.name"


snippets : Translations -> String
snippets translations =
    t translations "titles.snippets"


sourceCode : Translations -> String
sourceCode translations =
    t translations "titles.source_code"


terms : Translations -> String
terms translations =
    t translations "titles.terms"


users : Translations -> String
users translations =
    t translations "titles.users"
