# fly.toml app configuration file generated for unpacking on 2023-07-26T07:12:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "unpacking"
primary_region = "cdg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
