/*
 * unpacking API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Buttons {
    #[serde(rename = "cancel")]
    pub cancel: String,
    #[serde(rename = "confirm")]
    pub confirm: String,
    #[serde(rename = "delete")]
    pub delete: String,
    #[serde(rename = "edit")]
    pub edit: String,
    #[serde(rename = "new_snippet")]
    pub new_snippet: String,
    #[serde(rename = "new_term")]
    pub new_term: String,
    #[serde(rename = "new_user")]
    pub new_user: String,
    #[serde(rename = "sign_in")]
    pub sign_in: String,
    #[serde(rename = "sign_out")]
    pub sign_out: String,
    #[serde(rename = "source")]
    pub source: String,
    #[serde(rename = "submit")]
    pub submit: String,
    #[serde(rename = "view")]
    pub view: String,
}

impl Buttons {
    pub fn new(cancel: String, confirm: String, delete: String, edit: String, new_snippet: String, new_term: String, new_user: String, sign_in: String, sign_out: String, source: String, submit: String, view: String) -> Buttons {
        Buttons {
            cancel,
            confirm,
            delete,
            edit,
            new_snippet,
            new_term,
            new_user,
            sign_in,
            sign_out,
            source,
            submit,
            view,
        }
    }
}


