/*
 * unpacking API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateSnippet {
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "media")]
    pub media: crate::models::Media,
    #[serde(rename = "link", skip_serializing_if = "Option::is_none")]
    pub link: Option<String>,
    #[serde(rename = "existing_authors")]
    pub existing_authors: Vec<uuid::Uuid>,
    #[serde(rename = "new_authors")]
    pub new_authors: Vec<String>,
    #[serde(rename = "terms")]
    pub terms: Vec<uuid::Uuid>,
}

impl CreateSnippet {
    pub fn new(text: String, media: crate::models::Media, existing_authors: Vec<uuid::Uuid>, new_authors: Vec<String>, terms: Vec<uuid::Uuid>) -> CreateSnippet {
        CreateSnippet {
            text,
            media,
            link: None,
            existing_authors,
            new_authors,
            terms,
        }
    }
}


