/*
 * unpacking API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dialogs {
    #[serde(rename = "confirm_title")]
    pub confirm_title: String,
}

impl Dialogs {
    pub fn new(confirm_title: String) -> Dialogs {
        Dialogs {
            confirm_title,
        }
    }
}


