/*
 * unpacking API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Forms {
    #[serde(rename = "authors")]
    pub authors: String,
    #[serde(rename = "edit")]
    pub edit: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "link")]
    pub link: String,
    #[serde(rename = "media")]
    pub media: String,
    #[serde(rename = "media_blog")]
    pub media_blog: String,
    #[serde(rename = "media_book")]
    pub media_book: String,
    #[serde(rename = "media_news")]
    pub media_news: String,
    #[serde(rename = "media_twitter")]
    pub media_twitter: String,
    #[serde(rename = "media_video")]
    pub media_video: String,
    #[serde(rename = "media_website")]
    pub media_website: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "on_email_empty")]
    pub on_email_empty: String,
    #[serde(rename = "on_length_less_than")]
    pub on_length_less_than: String,
    #[serde(rename = "on_name_empty")]
    pub on_name_empty: String,
    #[serde(rename = "on_password_empty")]
    pub on_password_empty: String,
    #[serde(rename = "on_snippet_empty")]
    pub on_snippet_empty: String,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "role")]
    pub role: String,
    #[serde(rename = "role_admin")]
    pub role_admin: String,
    #[serde(rename = "role_user")]
    pub role_user: String,
    #[serde(rename = "related")]
    pub related: String,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "terms")]
    pub terms: String,
}

impl Forms {
    pub fn new(authors: String, edit: String, email: String, link: String, media: String, media_blog: String, media_book: String, media_news: String, media_twitter: String, media_video: String, media_website: String, name: String, on_email_empty: String, on_length_less_than: String, on_name_empty: String, on_password_empty: String, on_snippet_empty: String, password: String, role: String, role_admin: String, role_user: String, related: String, text: String, terms: String) -> Forms {
        Forms {
            authors,
            edit,
            email,
            link,
            media,
            media_blog,
            media_book,
            media_news,
            media_twitter,
            media_video,
            media_website,
            name,
            on_email_empty,
            on_length_less_than,
            on_name_empty,
            on_password_empty,
            on_snippet_empty,
            password,
            role,
            role_admin,
            role_user,
            related,
            text,
            terms,
        }
    }
}


