/*
 * unpacking API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Labels {
    #[serde(rename = "loading")]
    pub loading: String,
    #[serde(rename = "no_snippets")]
    pub no_snippets: String,
    #[serde(rename = "no_terms")]
    pub no_terms: String,
    #[serde(rename = "no_users")]
    pub no_users: String,
    #[serde(rename = "on_error")]
    pub on_error: String,
    #[serde(rename = "on_sign_out")]
    pub on_sign_out: String,
    #[serde(rename = "video_thumbnail")]
    pub video_thumbnail: String,
}

impl Labels {
    pub fn new(loading: String, no_snippets: String, no_terms: String, no_users: String, on_error: String, on_sign_out: String, video_thumbnail: String) -> Labels {
        Labels {
            loading,
            no_snippets,
            no_terms,
            no_users,
            on_error,
            on_sign_out,
            video_thumbnail,
        }
    }
}


