/*
 * unpacking API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MediaStatsResponse {
    #[serde(rename = "media")]
    pub media: crate::models::Media,
    #[serde(rename = "count")]
    pub count: i64,
}

impl MediaStatsResponse {
    pub fn new(media: crate::models::Media, count: i64) -> MediaStatsResponse {
        MediaStatsResponse {
            media,
            count,
        }
    }
}


