/*
 * unpacking API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Media {
    #[serde(rename = "Blog")]
    Blog,
    #[serde(rename = "Book")]
    Book,
    #[serde(rename = "News")]
    News,
    #[serde(rename = "Twitter")]
    Twitter,
    #[serde(rename = "Video")]
    Video,
    #[serde(rename = "Website")]
    Website,

}

impl ToString for Media {
    fn to_string(&self) -> String {
        match self {
            Self::Blog => String::from("Blog"),
            Self::Book => String::from("Book"),
            Self::News => String::from("News"),
            Self::Twitter => String::from("Twitter"),
            Self::Video => String::from("Video"),
            Self::Website => String::from("Website"),
        }
    }
}

impl Default for Media {
    fn default() -> Media {
        Self::Blog
    }
}




