/*
 * unpacking API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "User")]
    User,
    #[serde(rename = "Admin")]
    Admin,

}

impl ToString for Role {
    fn to_string(&self) -> String {
        match self {
            Self::User => String::from("User"),
            Self::Admin => String::from("Admin"),
        }
    }
}

impl Default for Role {
    fn default() -> Role {
        Self::User
    }
}




