/*
 * unpacking API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SnippetSearchResponse {
    #[serde(rename = "pages")]
    pub pages: i64,
    #[serde(rename = "snippets")]
    pub snippets: Vec<crate::models::SnippetResponse>,
}

impl SnippetSearchResponse {
    pub fn new(pages: i64, snippets: Vec<crate::models::SnippetResponse>) -> SnippetSearchResponse {
        SnippetSearchResponse {
            pages,
            snippets,
        }
    }
}


