/*
 * unpacking API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SnippetResponse {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "media")]
    pub media: crate::models::Media,
    #[serde(rename = "link", skip_serializing_if = "Option::is_none")]
    pub link: Option<String>,
    #[serde(rename = "authors")]
    pub authors: Vec<crate::models::AuthorResponse>,
    #[serde(rename = "terms")]
    pub terms: Vec<crate::models::SnippetTermResponse>,
}

impl SnippetResponse {
    pub fn new(id: uuid::Uuid, text: String, media: crate::models::Media, authors: Vec<crate::models::AuthorResponse>, terms: Vec<crate::models::SnippetTermResponse>) -> SnippetResponse {
        SnippetResponse {
            id,
            text,
            media,
            link: None,
            authors,
            terms,
        }
    }
}


