/*
 * unpacking API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StatsResponse {
    #[serde(rename = "media")]
    pub media: Vec<crate::models::MediaStatsResponse>,
}

impl StatsResponse {
    pub fn new(media: Vec<crate::models::MediaStatsResponse>) -> StatsResponse {
        StatsResponse {
            media,
        }
    }
}


