/*
 * unpacking API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TermResponse {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "related")]
    pub related: Vec<uuid::Uuid>,
}

impl TermResponse {
    pub fn new(id: uuid::Uuid, name: String, related: Vec<uuid::Uuid>) -> TermResponse {
        TermResponse {
            id,
            name,
            related,
        }
    }
}


