/*
 * unpacking API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TermGraphResponse {
    #[serde(rename = "terms")]
    pub terms: Vec<String>,
    #[serde(rename = "nodes")]
    pub nodes: Vec<Vec<i32>>,
}

impl TermGraphResponse {
    pub fn new(terms: Vec<String>, nodes: Vec<Vec<i32>>) -> TermGraphResponse {
        TermGraphResponse {
            terms,
            nodes,
        }
    }
}


