/*
 * unpacking API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Titles {
    #[serde(rename = "home")]
    pub home: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "snippets")]
    pub snippets: String,
    #[serde(rename = "source_code")]
    pub source_code: String,
    #[serde(rename = "stats")]
    pub stats: String,
    #[serde(rename = "terms")]
    pub terms: String,
    #[serde(rename = "users")]
    pub users: String,
}

impl Titles {
    pub fn new(home: String, name: String, snippets: String, source_code: String, stats: String, terms: String, users: String) -> Titles {
        Titles {
            home,
            name,
            snippets,
            source_code,
            stats,
            terms,
            users,
        }
    }
}


