/*
 * unpacking API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TokenResponse {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "role")]
    pub role: crate::models::Role,
}

impl TokenResponse {
    pub fn new(id: uuid::Uuid, token: String, role: crate::models::Role) -> TokenResponse {
        TokenResponse {
            id,
            token,
            role,
        }
    }
}


