/*
 * unpacking API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Translation {
    #[serde(rename = "buttons")]
    pub buttons: Box<crate::models::Buttons>,
    #[serde(rename = "titles")]
    pub titles: Box<crate::models::Titles>,
    #[serde(rename = "dialogs")]
    pub dialogs: Box<crate::models::Dialogs>,
    #[serde(rename = "forms")]
    pub forms: Box<crate::models::Forms>,
    #[serde(rename = "labels")]
    pub labels: Box<crate::models::Labels>,
}

impl Translation {
    pub fn new(buttons: crate::models::Buttons, titles: crate::models::Titles, dialogs: crate::models::Dialogs, forms: crate::models::Forms, labels: crate::models::Labels) -> Translation {
        Translation {
            buttons: Box::new(buttons),
            titles: Box::new(titles),
            dialogs: Box::new(dialogs),
            forms: Box::new(forms),
            labels: Box::new(labels),
        }
    }
}


