/*
 * unpacking API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateTerm {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "related")]
    pub related: Vec<uuid::Uuid>,
}

impl UpdateTerm {
    pub fn new(name: String, related: Vec<uuid::Uuid>) -> UpdateTerm {
        UpdateTerm {
            name,
            related,
        }
    }
}


