/*
 * unpacking API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserResponse {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "role")]
    pub role: crate::models::Role,
}

impl UserResponse {
    pub fn new(id: uuid::Uuid, name: String, email: String, role: crate::models::Role) -> UserResponse {
        UserResponse {
            id,
            name,
            email,
            role,
        }
    }
}


